providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd nextjs_space && npm install"]

[phases.build]
cmds = ["cd nextjs_space && npm install && npx prisma generate && npm run build"]

[phases.start]
cmds = ["cd nextjs_space && npx prisma db push && npm run start"]
